
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 24 22:27:43 SGT 2011
//----------------------------------------------------

package simPLparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 21;
  public static final int AND = 23;
  public static final int ELSE = 28;
  public static final int NEG = 25;
  public static final int PLUS = 19;
  public static final int OR = 24;
  public static final int RPAREN = 11;
  public static final int INT = 14;
  public static final int THEN = 27;
  public static final int EQUAL = 16;
  public static final int IN = 30;
  public static final int RCURLY = 13;
  public static final int END = 8;
  public static final int IDENTIFIER = 2;
  public static final int GREATER = 18;
  public static final int TRUE = 4;
  public static final int IF = 26;
  public static final int LPAREN = 10;
  public static final int RECFUN = 6;
  public static final int LCURLY = 12;
  public static final int EOF = 0;
  public static final int DIV = 22;
  public static final int MINUS = 20;
  public static final int FALSE = 5;
  public static final int error = 1;
  public static final int ARROW = 9;
  public static final int LET = 29;
  public static final int BOOL = 15;
  public static final int INTEGER = 3;
  public static final int LESS = 17;
  public static final int FUN = 7;
}

