package cVML;

public class OPCODES {
  public static final byte
      AND      =  0,
      CALL     =  1,
      DIV      =  2,
      DONE     =  3,
      EQUAL    =  4,
      GOTO     =  5,
      GREATER  =  6,
      JOF      =  7,
      LD       =  8,
      LDCB     =  9,
      LDCI     = 10,
      LDF      = 11,
      LDRF     = 12,
      LESS     = 13,
      MINUS    = 14,
      NOT      = 15,
      OR       = 16,
      PLUS     = 17,
      RTN      = 18,
      TIMES    = 19,
      UMINUS   = 20,
      TAILCALL = 21,
      DOT      = 22,
      HASP     = 23,
      EMPTY    = 24,
      RCD      = 25,
      THROW    = 26,
      TRY      = 27,
      ENDTRY   = 28,
      ASSIGN   = 29,
      RASSIGN  = 30,
      LDCP     = 31,
      POP      = 32,
      LOOKUP   = 33,
      STARTTHREAD = 34,
      ENDTHREAD   = 35,
      WAIT        = 36,
      SIGNAL      = 37,
      PRINT       = 38,
      START       = 39;
}
