
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 23 11:59:38 SGT 2011
//----------------------------------------------------

package imPLparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 28;
  public static final int HASPROPERTY = 36;
  public static final int EMPTY = 34;
  public static final int INTEGER = 4;
  public static final int LPAREN = 11;
  public static final int GREATER = 15;
  public static final int LESS = 14;
  public static final int MINUS = 17;
  public static final int RECFUN = 7;
  public static final int RPAREN = 12;
  public static final int SEMICOLON = 39;
  public static final int AND = 20;
  public static final int FUN = 8;
  public static final int IN = 27;
  public static final int OR = 21;
  public static final int COMMA = 32;
  public static final int DIV = 19;
  public static final int PLUS = 16;
  public static final int ASSIGN = 40;
  public static final int IF = 23;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int RBRACKET = 29;
  public static final int EQUAL = 13;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int PAIR = 30;
  public static final int TIMES = 18;
  public static final int ARROW = 10;
  public static final int COLON = 31;
  public static final int NEG = 22;
  public static final int ELSE = 25;
  public static final int WHILE = 37;
  public static final int LET = 26;
  public static final int PROPERTY = 3;
  public static final int THEN = 24;
  public static final int END = 9;
  public static final int FALSE = 6;
  public static final int DO = 38;
  public static final int PRINT = 35;
  public static final int IDENTIFIER = 2;
}

