
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 18 00:54:13 SGT 2011
//----------------------------------------------------

package ePLparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 14;
  public static final int MINUS = 11;
  public static final int INTEGER = 2;
  public static final int TRUE = 3;
  public static final int GREATER = 9;
  public static final int EQUAL = 7;
  public static final int PLUS = 10;
  public static final int EOF = 0;
  public static final int FALSE = 4;
  public static final int DIV = 13;
  public static final int LESS = 8;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int TIMES = 12;
  public static final int NEG = 16;
  public static final int LPAREN = 5;
  public static final int OR = 15;
}

